### PR TITLE
Adding Collection API

### PR DESCRIPTION
**Pull request by mainstringargs**

### CODE REVIEW

**Comment by mainstringargs** [comment]
Created a pull request.   Haven't done one before; not quite sure how to resolve it

**Comment by JonoAugustine** [comment]
Looks good. Can you add any more detail to the javadocs (What midlands is, @author, requires authorization?, etc). If you could link to or add an example JSON (in resource dir) that would be great as well, not really needed but something we are trying to keep up with (so finding API responses can be easier). Since this branch is behind the master there are a lot of changes, but I will update the compatibility issues.

I hope that's not too much to ask, we really appreciate you adding to the project!! 
(edit: This will def get pulled, just need some more docs)

**Comment by mainstringargs** [comment]
I'll add some more documentation.  Unfortunately I don't know what "midlands" is or what it actually means.  I figured it out by watching network requests in chrome dev console because I wanted to be able to access stocks by collection.

**Comment by JonoAugustine** [comment]
Thanks for updating! In review now.

**Comment by JonoAugustine** [comment]
This all looks good fundamentally (no pun intended) but it is still significantly behind the current master branch (your fork is from Conrad's original project).

Here are the needed changes:
ApiElement & ApiElementList  should be implemented/extended for response wrappers. Something like this:
```java
//Alternative for InstrumentFundimentalListElement
public class CollectionsElement implements ApiElement {
   String slug;
   String name;
   String description;
   List<InstrumentElement> instrumentList;
  //Other stuff...
}
```
So nothing needs to get re-written and generics can be used.

The ``InstrumentFundimentaElement`` was done away with in favor for the ``InstrumentElement`` (they were just duplicates that existed for some reason, it's also a much shorter name).

``ApiMethods`` have a simpler way of adding parameters now (removed the whole ``.parameter`` package in favor of simple maps in ApiMethod).

There are other major changes from Conrad's project, so take your time looking over them if possible.
If you have any questions just ask and thank you again for contributing!

Edit: If you want a very fast response, join the [discord server](https://discord.gg/VF7FctD)

**Comment by mainstringargs** [comment]
Ok, I merged in your fork and updated the code to at least fit into your structure and work.  The list returned doesn't exactly fit into the ApiElementList structure for deserializing (See example response here:  https://github.com/mainstringargs/Unofficial-Robinhood-Api/blob/master/resources/collection-response-100-most-popular.json).

**Comment by JonoAugustine** [comment]
Yeah, I noticed the returns aren't the same for whatever reason (thank RH) but It can fit as an Api*Element* instead, since it's not paginated or anything. I will look over the updated code and get back as soon as possible

**Pull request merged**
