### PR TITLE
Adding Rating Element API

### PR DESCRIPTION
**Pull request by mainstringargs**
Logic to access the Buy / Sell / Hold ratings available in Robinhood Web

### CODE REVIEW

**Comment by mainstringargs** [comment]
I realize you may not want/need this change, but I already had it coded up for myself and figured you may want to take a look.

**Comment by JonoAugustine** [comment]
Thanks for the submission, in review now

**Comment by JonoAugustine** [comment]
Looks good, but has not worked for me.
```java
package com.ampro.robinhood.endpoint.ratings;

import com.ampro.robinhood.BaseTest;
import com.ampro.robinhood.endpoint.ratings.data.RatingElementList;
import org.junit.Assert;
import org.junit.Test;

import static org.junit.Assert.assertEquals;

public class RatingsTest extends BaseTest {

    @Test
    public void getRatingsData() {
        RatingElementList ratings = api
                .getRatingsByInstrumentIds(tenTickers.toArray(new String[10]));
                //.getRatingsByInstrumentIds(tenTickers.get(0));
        System.err.println(ratings);
        assertEquals(10, ratings.getResults().size());
        ratings.getResults().forEach(Assert::assertNotNull);
    }
}
```


For future reference, please include JUnit tests (especially with public data); this hasn't been stipulated in the Contributing guidelines (it is rather new so it's ok for now). you can run JUnit tests with ``gradle test``.  if you need anymore help ask around on the [discord](https://discordapp.com/invite/VF7FctD), I can help with IntelliJ gradle stuff, but eclipse might need someone else

**Comment by mainstringargs** [comment]
Added unit tests.  Looks to be working now.

**Comment by JonoAugustine** [comment]
Looks good, getting merged now 👍

**Review by JonoAugustine — APPROVED** [review]
Merges getting pushed in a little while. ~~One note, the parameters named "ids" were noted as "tickers" in the Docs to be more clear. Not sure why the api asks for a query named "ids" but as long as it's just the stock ticker we should be consistent & clear~~

**Comment by mainstringargs** [comment]
It’s not taking the tickers directly. It takes the instrument ids. I made a
convenience method in RobinhoodApi that takes the tickets and grabs the
relevant instrument ids.

**Comment by JonoAugustine** [comment]
Ah my mistake, thank you for pointing that out. (*frantically undoes changes*)

**Pull request merged**
